version: '3.4'

services:
    mongo:
        container_name: marketplace-mongo
        image: 'mongo:4.4'
        volumes:
            - './data/mongo_4.4:/data/db'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
    api:
        container_name: marketplace-api
        build:
            context: ./api
            dockerfile: ./.docker/nodejs/Dockerfile
            target: prod
            args:
                - 'USR_DB_CONN=${USR_DB_CONN}'
                - 'USR_DB_NAME=${USR_DB_NAME}'
        environment:
            USR_DB_CONN: '${USR_DB_CONN}'
            USR_DB_NAME: '${USR_DB_NAME}'
            USR_PASSWORD_KEY: '${USR_PASSWORD_KEY}'
            USR_JWT_SECRET: '${USR_JWT_SECRET}'
        ports:
            - '0.0.0.0:${API_PORT}:3000'
        depends_on:
            - mongo
    web:
        container_name: marketplace-web
        build:
            context: ./web
            dockerfile: ./.docker/Dockerfile
        ports:
            - '0.0.0.0:${WEB_PORT}:8080'
        depends_on:
            - api
        links:
            - 'api:marketplace-api'