version: '3.4'
networks:
  default:
    name: GAIA
    external: true

services:
  nodejs:
    container_name: marketplace-api
    build:
      dockerfile: ./nodejs/Dockerfile
      target: base
    environment:
      - VIRTUAL_HOST=marketplace-api.localhost
      - VIRTUAL_PORT=3000
      - USR_DB_CONN=mongodb://gaia:password@local_mongo:27017/?authSource=admin
      - USR_DB_NAME=prueba
      - USR_PASSWORD_KEY=loremipsum
      - USR_JWT_SECRET=My!@!Se3cr8tH4sh
    volumes:
      - '../:/usr/src/app'
    command: npm run dev
